version: 2

# Set up the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "18"
    rust: "1.64"
    golang: "1.19"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt